pub mod agent;
pub mod compaction;
pub mod context_pruning;
pub mod failover;
pub mod loop_detection;
pub mod model_registry;
pub mod prompt;
pub mod provider;
pub mod providers;
pub mod result_compaction;
pub mod retry;
pub mod slash_commands;
pub mod thinking;

pub use agent::{run_agent, run_agent_streaming, AgentConfig, AgentResult};
pub use compaction::{CompactionConfig, CompactionResult, compact_session};
pub use context_pruning::{PruningConfig, prune_context};
pub use failover::FailoverChain;
pub use loop_detection::{LoopDetector, LoopStatus};
pub use model_registry::{ModelCapabilities, ModelInfo, ModelRegistry};
pub use prompt::SystemPromptBuilder;
pub use provider::LlmProvider;
pub use providers::{AnthropicProvider, OllamaProvider, OpenAiProvider, create_provider, list_providers, ApiType, ProviderDef};
pub use result_compaction::{ResultCompactionConfig, CompactedResult, ResultCompactor};
pub use retry::{RetryConfig, RetryCondition, RetryState, with_retry, with_retry_status};
pub use thinking::{ThinkingConfig, ThinkingLevel};
